//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWaltPOS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeWaltPOSEntities : DbContext
    {
        public DeWaltPOSEntities()
            : base("name=DeWaltPOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BestPracticeType> BestPracticeTypes { get; set; }
        public DbSet<ProductType> ProductTypes { get; set; }
        public DbSet<RelatedProduct> RelatedProducts { get; set; }
        public DbSet<ThumbImage> ThumbImages { get; set; }
        public DbSet<PanelType> PanelTypes { get; set; }
        public DbSet<RelatedPanel> RelatedPanels { get; set; }
        public DbSet<API_KEY_TABLE> API_KEY_TABLE { get; set; }
        public DbSet<APITimestamp> APITimestamps { get; set; }
        public DbSet<RelatedFixture> RelatedFixtures { get; set; }
        public DbSet<CatalogueImage> CatalogueImages { get; set; }
        public DbSet<Brand> Brands { get; set; }
        public DbSet<Thumbsmall> Thumbsmalls { get; set; }
        public DbSet<Product> Products { get; set; }
    }
}
