//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWaltPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanelType
    {
        public PanelType()
        {
            this.RelatedPanels = new HashSet<RelatedPanel>();
            this.Products = new HashSet<Product>();
        }
    
        public int PanelId { get; set; }
        public string PanelCode { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<RelatedPanel> RelatedPanels { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
