//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWaltPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedFixture
    {
        public int ProductID { get; set; }
        public int RelatedFixture1 { get; set; }
        public Nullable<bool> Flag { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
