//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWaltPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThumbImage
    {
        public int id { get; set; }
        public Nullable<int> prodid { get; set; }
        public string image { get; set; }
        public Nullable<int> language { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
